[package]
name = "color-scheme-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
ashpd = "0.6.2"
async-std = { version = "1.12.0", features = ["attributes"] }
futures-core = "0.3.28"
gio = "0.17.2"
pin-project-lite = "0.2.13"
