name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ubuntu-latest-cargo-build-nightly-${{ hashFiles('**/Cargo.toml') }}
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
        components: rustfmt, clippy
        override: true
    - name: Build
      run: cargo build
    - name: Check format
      run: cargo fmt --all -- --check
    - name: Run clippy with native dev features
      run: cargo clippy --all-targets -- --deny warnings
